#lcoal
database:
  driverName: mysql
  host: 8.210.48.242
  port: "3306"
  databaseName: pool
  username: root
  password: Test20220303
  charset: utf8mb4
  loc: Asia/Shanghai

#nodes:
#  length: 1
#  node0: "https://data-seed-prebsc-2-s2.binance.org:8545/"

node: "https://data-seed-prebsc-2-s2.binance.org:8545/"
moralis:
  url: "https://deep-index.moralis.io/api/v2/"
  chainId: "0x61"
  key: "dXEk5PiV0qmNUHfKeEWdrf9Iu8OpanzXHRi3tLzAxxf9rwShOECim67VeQJdjwbv"

controllerAddress: "0x099651e3BaaE396b2DB2E9C5A33D54571e291680"